server:
  port: 8082

spring:
  datasource:
    name: ufagent
    //url: jdbc:mysql://10.10.66.8:3306/ufagent?characterEncoding=utf-8&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/ufagent?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
    //password: 
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20


mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ufgov.ufagent.domain

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

